title: PQC introduction

description: 整理后量子密码学知识,以及NIST的PQC标准

theme: just-the-docs

url: https://habezai.github.io/PQC

aux_links:
  本项目的Repository: https://github.com/habezai/PQC

logo: "/assets/images/PQC.png"

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

